My environment has newer jdk (java 15) and kojo doesn't build with it. So, switch to: ben@Bulents-MacBook-Pro kojo % java -version java version "1.8.0_271" Java(TM) SE Runtime Environment (build 1.8.0_271-b09) Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
Java 15 details and errors:
Starting the build in /Users/ben/src/kojo/git/kojo
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
+ rm -rf dist
+ ./sbt.sh clean test buildDist
Unrecognized VM option 'CMSClassUnloadingEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
+ rm -rf installerbuild
+ mkdir -p installerbuild/lib
+ cd installer
+ scala cp-staging-jars.scala
-- [E103] Syntax Error: /Users/ben/src/kojo/git/kojo/installer/cp-staging-jars.scala:6:0
6 |jars.getLines.foreach { j =>
  |^^^^
  |Illegal start of toplevel definition

longer explanation available when compiling with `-explain`
1 error found
Error: Errors encountered during compilation